name: Build Docker Image from DevContainer

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DEV_GITHUB_TOKEN }}

    - name: Clean Up Environment
      run: |
        sudo bash ./scripts/envcleaner.sh

    - name: Build Docker image from devcontainer.json
      run: |
        # Build the Docker image using the devcontainer.json configuration
        npm install -g @devcontainers/cli 
        devcontainer build --workspace-folder . --image-name jamesmith0817/net-storage:latest

    - name: Save Docker image to tar
      run: |
        # Save the built Docker image to a tar file
        docker save jamesmith0817/net-storage:latest -o net-storage.tar  

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: devcontainer-image
        path: net-storage.tar